### ISSUE TITLE
Galleria not loading properly in Firefox, IE. 

### ISSUE THREAD

**Issue by prastut** [worseisbetter/galleria#374] opened 2016-09-17 16:27 UTC
I am using Galleria in my portfolio website. Usage of Galleria can be found on https://prastut.github.io/Cambuzz/

The problem is that Galleria loads perfectly on Chrome, but is unable to do so in Firefox, IE. What is shows in IE:

* It loads everything. There's no error saying Galleria cannot be found.  The black background is there, with all the images being shown in the bottom bar. 
* When you click the next button to change to a different picture, it doesn't do anything. 

While this setup perfectly works on Chrome, it doesn't on the browsers mentioned in the issue.

**Comment by aibon** [comment] 2016-09-17 20:38
It does not work in Chrom either, please check that your html is correct. You probably have a missing closing tag or something like that in your markup. http://validator.w3.org. 

If that's not the case, first try to isolate the gallery on a own page and find out what parts of your site lead perhaps to a conflict.

**Closed** 2016-09-17 20:50 UTC

**Comment by prastut** [comment] 2016-09-17 22:11
Hi @aibon thank you for your time. 

Following are the steps I followed:
* Checked the markup on the website you had provided. Didn't have any errors that I think would be related to Galleria, even though fixed them. +1 for the link. 
* Isolated the gallery on an another page. There are no console errors, Galleria even loads properly but I just can't move to the next image. 

Some background:
* I am using Hexo, a static website generator which I hardly think has to do anything with the error. It's just compiling ejs for all I know. 
* I am using galleria.js which is served online. If I use an offline version, it results in assignment errors or something of that. I can't even trace it in the file, let alone debug it. 

Let me know your opinions.

**Comment by aibon** [comment] 2016-09-17 22:37
i just isolated galleria from your page and stripped everything not relevant and it works like it should. 

https://gist.github.com/aibon/fbcce187c5a9d022d1a5dc82cdfcd505

so the problem is a conflict somewhere on your site. try adding some stuff and see if it still works. sorry i can't help you further.
